---
- hosts: all
  gather_facts: true
  tasks:
  - name: Install package baseline
    apt:
      name:
        - vim
        - wget
        - curl
        - net-tools
        - dnsutils
        - nodejs
        - cron
        - lsof
        - bash-completion
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: Change time zone
    shell: echo "Europe/Zurich" > /etc/timezone; ln -sf /usr/share/zoneinfo/Europe/Zurich /etc/localtime
    when: ansible_os_family == "Debian"