---

- copy: "src=apache2.conf dest=/etc/apache2/apache2.conf"
  name: "apache2.conf file"
  notify:
    - "restart apache2"

- copy: "src=index.html dest=/var/www/html/index.html"
  name: "send index.html"